services:
  nestjs-app:
    image: nestjs-handsup-api:latest
    container_name: nestjs-handsup-api
    ports:
      - "8081:8081"
    env_file:
      - .env
    networks:
      - docker-network

networks:
  docker-network:
    external: true