export enum BadgeCode {
  ANNUAL_MVP_2024 = 'ANNUAL_MVP_2024',
  S_GRADE_H1_H2 = 'S_GRADE_H1_H2',
  JOB_EXP_OVER_1700 = 'JOB_EXP_OVER_1700C',
  EXP_EVERY_MONTH_FOR_A_YEAR = 'EXP_EVERY_MONTH_FOR_A_YEAR',
  COMPANY_PROJECT_OVER_5 = 'COMPANY_PROJECT_OVER_5',
  MONTH_SPECIAL_JOB_OVER_6 = 'MONTH_SPECIAL_JOB_OVER_6',
}
