services:
# Database for Development. (PORT 3306)
  dev-db:
    image: mysql/mysql-server:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=docker-mysql-db
    volumes:
      - ./data:/var/lib/mysql