name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: nestjs-handsup-api

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          touch .env
          cat << EOF >> .env
          ${{ secrets.ENV }}

      - name: Build Docker Image
        run: |
          docker buildx create --use
          docker buildx build --load --platform linux/arm64 -t nestjs-handsup-api .
          docker images
          docker save nestjs-handsup-api:latest -o nestjs-handsup-api.tar
          chmod 664 nestjs-handsup-api.tar
          ls -al

      - name: Copy file to Raspberry Pi
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.RASPBERRY_HOST }}
          username: ${{ secrets.RASPBERRY_USERNAME }}
          password: ${{ secrets.RASPBERRY_PASSWORD }}
          port: ${{ secrets.RASPBERRY_PORT }}
          source: 'nestjs-handsup-api.tar,Dockerfile,docker-compose.yml,.env'
          target: '~/Docker/service/handsup-api'

      - name: Deploy Docker Image on Remote Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.RASPBERRY_HOST }}
          username: ${{ secrets.RASPBERRY_USERNAME }}
          password: ${{ secrets.RASPBERRY_PASSWORD }}
          port: ${{ secrets.RASPBERRY_PORT }}
          script: |
            cd Docker/service/handsup-api
            ls -al
            docker load < nestjs-handsup-api.tar
            rm nestjs-handsup-api.tar
            docker-compose down || true
            docker-compose up -d
